CREATE TABLE USER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(128),
    ACCOUNT_ID VARCHAR(128),
    TOKEN VARCHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT
);
COMMENT ON COLUMN USER.ID IS '';
COMMENT ON COLUMN USER.NAME IS '';
COMMENT ON COLUMN USER.ACCOUNT_ID IS '';
COMMENT ON COLUMN USER.TOKEN IS '';
COMMENT ON COLUMN USER.GMT_CREATE IS '';
COMMENT ON COLUMN USER.GMT_MODIFIED IS '';